project:
  type: website
  output-dir: docs

website:
  title: "Shane Curtis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hello.qmd
        text: My python page

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



