project:
  type: website
  output-dir: docs

website:
  title: "Shane Curtis"
  favicon: E-Portfolio_Logo.png  
  navbar:
    title: false
    logo: E-Portfolio_Logo.png  
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hello.qmd
        text: My Python Page

format:
  html:
    theme:
      - cosmo
      - brand



