project:
  type: website
  output-dir: docs

website:
  title: "Shane Curtis"
  favicon: Icon_New.png  
  navbar:
    title: false
    logo: Icon_New.png  
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hello.qmd
        text: My Python Page

format:
  html:
    theme: 
      - minty
      - styles.scss
    mainfont: Lora
    toc: false
    page-layout: full





