project:
  type: website
  output-dir: docs

website:
  title: "Shane Curtis"
  favicon: Moneywall.png
  navbar:
    title: false
    logo: E-Portfolio_Logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hello.qmd
        text: My python page

format:
  html:
    theme:
      - cosmo
      - brand



